(define (problem TEST)
    (:domain sokoban)
    (:objects Mario box1 box2 box3 box4 cell1 cell2 cell3 cell4 cell5 cell6 cell7 cell8 cell9 cell10 cell11 cell12)
    (:init 
        (worker Mario)
        (box box1)
        (box box2)
        (box box3)
        (box box4)
        ;CELLS
        (cell cell1)
        (cell cell2)
        (cell cell3)
        (cell cell4)
        (cell cell5)
        (cell cell6)
        (cell cell7)
        (cell cell8)
        (cell cell9)
        (cell cell10)
        (cell cell11)
        (cell cell12)
        ;LOCATIONS
        (atw Mario cell6)
        (atb box1 cell2)
        (atb box2 cell5)
        (atb box3 cell7)
        (atb box4 cell9)
        ;FREE
        (free cell1)
        (free cell3)
        (free cell4)
        (free cell8)
        (free cell10)
        (free cell11)
        (free cell12)
        ;UP
        (up cell2 cell6)
        (up cell6 cell8)
        (up cell5 cell7)
        (up cell7 cell11)
        (up cell11 cell12)
        ;DOWN
        (down cell2 cell1)
        (down cell6 cell2)
        (down cell7 cell5)
        (down cell8 cell6)
        (down cell11 cell7)
        ;LEFT
        (left cell4 cell3)
        (left cell5 cell4)
        (left cell6 cell5)
        (left cell8 cell7)
        (left cell9 cell8)
        ;RIGHT
        (right cell4 cell5)
        (right cell5 cell6)
        (right cell7 cell8)
        (right cell8 cell9)
        (right cell9 cell10)
    )
    (:goal (and
        (atb box1 cell1)
        (atb box2 cell3)
        (atb box3 cell12)
        (atb box4 cell10))
    )
)